---
kind: pipeline
name: scan-build

steps:
    - name: bootstrap
      image: signalwire/freeswitch-public-base
      pull: true
      commands:
      - ./autogen.sh

    - name: configure
      image: signalwire/freeswitch-public-base
      pull: true
      commands:
      - ./configure --with-pic --with-glib=no --disable-shared --without-doxygen --disable-stun

    - name: scan-build
      image: signalwire/freeswitch-public-base
      pull: true
      commands:
      - apt-get update && apt-get install -y clang-tools-7 
      - mkdir -p scan-build
      - echo '#!/bin/bash\nscan-build-7 -o ./scan-build/ make -j`nproc --all` |& tee ./scan-build-result.txt\nexitstatus=$${PIPESTATUS[0]}\necho $$exitstatus > ./scan-build-status.txt\n' > scan.sh
      - chmod +x scan.sh
      - ./scan.sh
      - exitstatus=`cat ./scan-build-status.txt`
      - echo "*** Exit status is $exitstatus"

    - name: notify
      image: signalwire/public-freeswitch-scan-build-notify
      pull: true
      environment:
        GITHUB_CI_APP_PEM:
          from_secret: github_ci_app_pem
        SSH_KEY:
          from_secret: public_artifacts_ssh_key
        SLACK_WEBHOOK_URL:
          from_secret: slack_webhook_url
      commands:
      - /root/notify.sh

      
trigger:
  branch:
  - master
  event:
  - pull_request
  - push

---
kind: signature
hmac: 3eb27f13c4a3d8dfb0f343d0b83675a06b754e50ad7b094a3381dea8b0017267

...
